sudo: required

services:
  - docker

branches:
  only:
  - master
  - /^v.*$/

before_install:
  - echo "start CI."

script:
  - echo "test successful."

after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - make push-image
